[package]
name = "extrae-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["sched","fs","hostname","feature"] }

[[bin]]
name = "program"
path = "src/program.rs"

[[bin]]
name = "visualizer"
path = "src/visualizer.rs"

