name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  extrae-rs-tests:
    name: Run extrae-rs tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --features profiling -- --nocapture

  extrae-rs-executables:
    name: Run extrae-rs executables
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build everything
        run: cargo build --features profiling

      - name: Run all executables
        run: |
           cargo run --bin program_declarative --features profiling
           cargo run --bin program_procedural --features profiling
           cargo run --bin program_tokio --features profiling
           cargo run --bin program_threads --features profiling

      - name: Run visualizer
        env:
          EXTRAE_SUFFIX: "mythreads"
        run: |
           cargo run --bin program_threads --features profiling
           cargo run --bin visualizer TRACEDIR_mythreads/Trace_1.bin


  extrae-rs-hwcounters:
    name: Run extrae-rs sw counter tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build everything
        run: cargo build --features profiling

      - name: Enable perf permissions
        run: sudo sysctl -w kernel.perf_event_paranoid=1

      - name: Run test threads
        env:
          EXTRAE_counters: "cpu-migrations,context-switches"
        run: |
           cargo run --bin program_declarative --features profiling
           cargo run --bin program_procedural --features profiling
           cargo run --bin program_tokio --features profiling
           cargo run --bin program_threads --features profiling

  coverage:
    name: Coverage on ubuntu
    runs-on: ubuntu-latest
    needs: [extrae-rs-tests, extrae-rs-executables, extrae-rs-hwcounters]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install grcov
        run: cargo install grcov

      - name: Install llvm-tools
        run: rustup component add llvm-tools-preview

      - name: Enable perf permissions
        run: sudo sysctl -w kernel.perf_event_paranoid=1

      - name: Run tests with coverage
        env:
          EXTRAE_counters: "cpu-migrations,context-switches"
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "extrae-rs-%p-%m.profraw"
        run: cargo test --features profiling -- --nocapture

      - name: Run visualizer with coverage
        env:
          EXTRAE_SUFFIX: "mythreads2"
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "extrae-rs-%p-%m.profraw"
        run: |
           cargo run --bin program_threads --features profiling
           cargo run --bin visualizer TRACEDIR_mythreads2/Trace_1.bin

      - name: Run grcov
        run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o ./lcov.info

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: ./lcov.info
