name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  extrae-rs-tests:
    name: Run extrae-rs tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --features profiling -- --nocapture

  extrae-rs-hwcounters:
    name: Run extrae-rs tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build everything
        run: cargo build --features profiling

      - name: Enable perf permissions
        run: sudo sysctl -w kernel.perf_event_paranoid=1

      - name: Run test threads
        env:
          EXTRAE_counters: "cpu-migrations"
        run: ./target/debug/program_threads
